# Generated by Django 4.2.7 on 2023-12-24 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_users_use_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='use_balance',
        ),
    ]
