# Generated by Django 4.2.7 on 2023-12-24 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_remove_users_use_balance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankCard',
        ),
    ]
