# Generated by Django 4.2.7 on 2023-12-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_delete_bankcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(max_length=50)),
                ('balance', models.DecimalField(decimal_places=2, default=10000000.0, max_digits=10)),
            ],
        ),
    ]
