# Generated by Django 4.2.7 on 2023-12-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_bank_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=10000000.0, max_digits=10),
        ),
    ]
