# Generated by Django 4.2.7 on 2023-12-25 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complished', models.CharField(max_length=20)),
                ('require_days', models.CharField(max_length=20)),
                ('project_name', models.CharField(max_length=20)),
                ('st_time', models.CharField(max_length=20)),
                ('ed_time', models.CharField(max_length=20)),
                ('chat_name', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
