# Generated by Django 4.2.7 on 2023-12-25 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='now_project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complished', models.CharField(max_length=20)),
                ('require_days', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='complished',
        ),
        migrations.RemoveField(
            model_name='project',
            name='require_days',
        ),
    ]
