# Generated by Django 4.2.7 on 2023-12-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=10)),
                ('explain', models.CharField(max_length=255)),
                ('ps', models.CharField(max_length=10)),
                ('title1', models.CharField(max_length=50)),
                ('title2', models.CharField(max_length=50)),
            ],
        ),
    ]
