# Generated by Django 4.2.7 on 2023-12-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='price_before',
            field=models.DecimalField(decimal_places=2, default=99.99, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drone',
            name='price_current',
            field=models.DecimalField(decimal_places=2, default=99.99, max_digits=10),
            preserve_default=False,
        ),
    ]
