# Generated by Django 4.2.7 on 2023-12-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drone', '0002_drone_price_before_drone_price_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='introduction',
            field=models.CharField(default='参数111', max_length=255),
        ),
        migrations.AddField(
            model_name='drone',
            name='op11',
            field=models.CharField(default='其他', max_length=100),
        ),
        migrations.AddField(
            model_name='drone',
            name='op12',
            field=models.CharField(default='其他', max_length=100),
        ),
        migrations.AddField(
            model_name='drone',
            name='op13',
            field=models.CharField(default='其他', max_length=100),
        ),
        migrations.AddField(
            model_name='drone',
            name='op14',
            field=models.CharField(default='其他', max_length=100),
        ),
        migrations.AddField(
            model_name='drone',
            name='op21',
            field=models.CharField(default='其他', max_length=100),
        ),
        migrations.AddField(
            model_name='drone',
            name='op22',
            field=models.CharField(default='其他', max_length=100),
        ),
        migrations.AddField(
            model_name='drone',
            name='op23',
            field=models.CharField(default='其他', max_length=100),
        ),
        migrations.AddField(
            model_name='drone',
            name='op24',
            field=models.CharField(default='其他', max_length=100),
        ),
        migrations.AddField(
            model_name='drone',
            name='op31',
            field=models.CharField(default='其他', max_length=100),
        ),
        migrations.AddField(
            model_name='drone',
            name='op32',
            field=models.CharField(default='其他', max_length=100),
        ),
        migrations.AddField(
            model_name='drone',
            name='op33',
            field=models.CharField(default='其他', max_length=100),
        ),
        migrations.AddField(
            model_name='drone',
            name='op34',
            field=models.CharField(default='其他', max_length=100),
        ),
        migrations.AddField(
            model_name='drone',
            name='select_1',
            field=models.CharField(default='属性', max_length=100),
        ),
        migrations.AddField(
            model_name='drone',
            name='select_2',
            field=models.CharField(default='属性', max_length=100),
        ),
        migrations.AddField(
            model_name='drone',
            name='select_3',
            field=models.CharField(default='属性', max_length=100),
        ),
        migrations.AddField(
            model_name='drone',
            name='use_case',
            field=models.CharField(default='适用场景111', max_length=255),
        ),
    ]
