# Generated by Django 4.2.7 on 2023-12-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drone', '0004_contact_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='img',
            field=models.ImageField(default=2, upload_to='img'),
            preserve_default=False,
        ),
    ]
