# Generated by Django 4.2.7 on 2023-12-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drone', '0005_drone_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='img',
            field=models.ImageField(default='static/images/UAV.svg', upload_to='img'),
        ),
    ]
