# Generated by Django 4.2.7 on 2023-12-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drone', '0006_alter_drone_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='img',
            field=models.ImageField(default='/statics/images/UAV.svg', upload_to='img'),
        ),
    ]
